version = 0.1

[default.global.parameters]
stack_name = "web-scraper-stack"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
