name: Deploy SAM App

on:
  push:
    branches: [ "main" ]   # deploy only from main branch
  workflow_dispatch:       # allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Install dependencies into layer
      #   run: |
      #     mkdir -p layer/python
      #     pip install hyperbrowser python-dotenv huggingface_hub -t layer/python

      - name: Build SAM app
        run: sam build
        working-directory: base

      - name: Deploy SAM app
        run: |
          sam deploy --no-confirm-changeset \
            --parameter-overrides \
              HyperbrowserApiKey=${{ secrets.HYPERBROWSER_API_KEY }} \
              HuggingFaceToken=${{ secrets.HF_TOKEN }}
